# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'LearningEnglishByVOA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LearningEnglishByVOA
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD'
  pod 'JSONKit'
  pod 'SWRevealViewController'
  pod 'Realm'
  pod 'Masonry'
  pod 'OpenSSL', '~> 1.0'
  pod 'SAMKeychain'
end
